### ISSUE TITLE
Install is not working on macOS 10.12.3 with go 1.8

### ISSUE THREAD

**Issue by jharris-** [Pryz/terraform-provider-ldap#1]
Thanks for posting this terraform provider.
I am not able to install this package by the recommended way or locally by running `go build`, `go get .`

I am new to go so sorry in advance if this is an error on my part.

```
$ go get -u github.com/Pryz/terraform-provider-ldap
# github.com/Pryz/terraform-provider-ldap
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"

$ go version
go version go1.8 darwin/amd64

$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
```

**Comment by Pryz** [comment]
My bad. I forgot the push the main. Should be good now.

Also, note that I didn't test this provider with Go 1.8

**Comment by jharris-** [comment]
Works now.

Thanks!
